// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../../app/db/entities/game_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 2858504651234027067),
      name: 'GameEntity',
      lastPropertyId: const IdUid(7, 494771101630273489),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2662572427038808879),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4127222710353328555),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7130661513575996674),
            name: 'level',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2884576583018888210),
            name: 'firstGame',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8786765053527608994),
            name: 'lastGame',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8826563733160735847),
            name: 'coin',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 2858504651234027067),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [494771101630273489],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    GameEntity: EntityDefinition<GameEntity>(
        model: _entities[0],
        toOneRelations: (GameEntity object) => [],
        toManyRelations: (GameEntity object) => {},
        getId: (GameEntity object) => object.id,
        setId: (GameEntity object, int id) {
          object.id = id;
        },
        objectToFB: (GameEntity object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.level);
          fbb.addInt64(3, object.firstGame.millisecondsSinceEpoch);
          fbb.addInt64(4, object.lastGame.millisecondsSinceEpoch);
          fbb.addInt64(5, object.coin);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final firstGameParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final coinParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final lastGameParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final object = GameEntity(
              name: nameParam,
              level: levelParam,
              firstGame: firstGameParam,
              coin: coinParam,
              lastGame: lastGameParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [GameEntity] entity fields to define ObjectBox queries.
class GameEntity_ {
  /// see [GameEntity.id]
  static final id =
      QueryIntegerProperty<GameEntity>(_entities[0].properties[0]);

  /// see [GameEntity.name]
  static final name =
      QueryStringProperty<GameEntity>(_entities[0].properties[1]);

  /// see [GameEntity.level]
  static final level =
      QueryIntegerProperty<GameEntity>(_entities[0].properties[2]);

  /// see [GameEntity.firstGame]
  static final firstGame =
      QueryIntegerProperty<GameEntity>(_entities[0].properties[3]);

  /// see [GameEntity.lastGame]
  static final lastGame =
      QueryIntegerProperty<GameEntity>(_entities[0].properties[4]);

  /// see [GameEntity.coin]
  static final coin =
      QueryIntegerProperty<GameEntity>(_entities[0].properties[5]);
}
